# from __future__ import generators
# from sqlalchemy.ext.declarative import declarative_base
# from sqlalchemy import create_engine,Column,Integer,VARBINARY,Identity,VARCHAR,NVARCHAR,DATETIME,CHAR,ForeignKey,NUMERIC,BOOLEAN
# from sqlalchemy.orm import sessionmaker,registry,relationship,Session
# from typing import List
# SERVER = '192.168.70.131'
# DATABASE = 'QLNV_ORM'
# DRIVER = 'SQL Server'
# USERNAME = 'WCFCom'
# PASSWORD = '123'
# DATABASE_CONNECTION = f'mssql://{USERNAME}:{PASSWORD}@{SERVER}/{DATABASE}?driver={DRIVER}'
# engine = create_engine(DATABASE_CONNECTION)
# connection = engine.connect()
# Session=sessionmaker(bind=engine)
# seccion=Session()
# Base=declarative_base()
# mapper_registry=registry()

# class SimpleTrip(Base):
#     __tablename__="TE_SimpleTrip"
#     TripNo=Column(VARCHAR(20),Identity(),primary_key=True)
#     ETP=Column(DATETIME)
#     ETA=Column(DATETIME)
#     CreateDate=Column(DATETIME)
#     CreateUser=Column(VARCHAR(20))
#     UpdateDate=Column(DATETIME)
#     UpdateUser=Column(VARCHAR(20))
#     IsUse=Column(CHAR(1))
#     EquipmentCode=Column(VARCHAR(20),ForeignKey("MA_Equipment.EquipmentCode"))
#     EquipmentDesc=Column(NVARCHAR(50))
#     DriverId=Column(VARCHAR(20),ForeignKey("MA_Equipment.EquipmentCode"))
#     DriverDesc=Column(NVARCHAR(200))
#     ATP=Column(DATETIME)
#     CompleteTime=Column(DATETIME)
#     TripStatus=Column(VARCHAR(20))
#     DCCode=Column(VARCHAR(20))
#     EquipTypeNo=Column(VARCHAR(20))
#     TripMemo=Column(NVARCHAR(500))
#     CODAmount=Column(NUMERIC(18,5))
#     ETD=Column(DATETIME)
#     ATD=Column(DATETIME)
#     BatchGroupNo=Column(VARCHAR(20))
#     SecurityCode=Column(VARCHAR(20))
#     LinkUpTripNo=Column(VARCHAR(20))
#     Vendor=Column(VARCHAR(20))
#     Porter=Column(VARCHAR(20))
# class SimpleOrder(Base):
#     __tablename__="TE_SimpleOrder"
#     OrderId=Column(Integer,Identity(),primary_key=True)
#     OrderNo=Column(VARCHAR(30))
#     Weight=Column(NUMERIC(18,5))
#     Volume=Column(NUMERIC(18,5))
#     ShipTo=Column(VARCHAR(50))
#     ShipToAddress=Column(NVARCHAR(500))
#     ShipToArea=Column(VARCHAR(50))
#     DeliveryDate=Column(DATETIME)
#     Priority=Column(Integer)
#     TripNo=Column(VARCHAR(20))
#     ArrivalTime=Column(DATETIME)
#     Qty=Column(NUMERIC(18,5))
#     ItemNote=Column(NVARCHAR(500))
#     DCCode=Column(VARCHAR(20))
#     ContactCode=Column(VARCHAR(20),ForeignKey("MA_Companys.ContactCode"),ForeignKey("MA_Contact"))
#     CreateDate=Column(DATETIME)
#     CreateUser=Column(VARCHAR(20))
#     UpdateDate=Column(DATETIME)
#     UpdateUser=Column(VARCHAR(20))
#     IsUse=Column(CHAR(1))
#     COD=Column(NUMERIC(18,5))
#     ActualAmount=Column(NUMERIC(18,5))
#     PickUp=Column(VARCHAR(50))
#     TripType=Column(VARCHAR(50))
#     CODAmount=Column(NUMERIC(18,5))
#     TransitOrgOrderId=Column(VARCHAR(20))
#     SplitOrderIndex=Column(Integer)
#     SplitOrgOrderId=Column(VARCHAR(20))
#     OtherRefNo1=Column(VARCHAR(50))
#     OtherRefNo2=Column(VARCHAR(50))
#     OtherRefNo3=Column(VARCHAR(50))
#     RequestGroup=Column(VARCHAR(30))
#     RequestTruckType=Column(VARCHAR(20))
#     OrgOrderId=Column(Integer)
# class MAStaff(Base):
#     __tablename__="MA_Staff"
#     StaffUserId=Column(VARCHAR(20),primary_key=True)
#     StaffName=Column(NVARCHAR(1600))
#     RoleType=Column(VARCHAR(20))
#     IsUse=Column(CHAR(1))
#     CreateDate=Column(DATETIME)
#     CreateUser=Column(VARCHAR(20))
#     UpdateDate=Column(DATETIME)
#     UpdateUser=Column(VARCHAR(20))
#     DCCode=Column(VARCHAR(20))
#     DefaultEquipment=Column(VARCHAR(20))
#     MobileNo=Column(VARCHAR(40))
#     StatusWorking=Column(VARCHAR(20))
#     ResignedDate=Column(DATETIME)
#     DriverLicenseNo=Column(VARCHAR(20))
#     DateOfJoined=Column(DATETIME)
#     ICNo=Column(VARCHAR(40))
#     VendorCode=Column(VARCHAR(20))
#     Remark=Column(NVARCHAR(500))
#     OldCode=Column(VARCHAR(20))
#     LacVietCode=Column(VARCHAR(20))
#     LeftDate=Column(DATETIME)
#     equement=relationship("MaEquiment",backref="MA_Staff")
# class MaEquiment(Base):
#     __tablename__="MA_Equipment"
#     EquipmentCode=Column(VARCHAR(20),primary_key=True)
#     EquipmentDesc=Column(NVARCHAR(1600))
#     IsUse=Column(VARCHAR(20))
#     CreateDate=Column(DATETIME)
#     CreateUser=Column(VARCHAR(20))
#     UpdateDate=Column(DATETIME)
#     UpdateUser=Column(VARCHAR(20))
#     Brand=Column(NVARCHAR(1600))
#     Model=Column(NVARCHAR(1600))
#     RefEquipCode=Column(NVARCHAR(50))
#     EquipTypeNo=Column(VARCHAR(20),ForeignKey("MA_EquipmentType.EquipTypeNo"))
#     Ownership=Column(VARCHAR(20))
#     Color=Column(VARCHAR(20))
#     PurchaseDate=Column(DATETIME)
#     PurchaseAmt=Column(NUMERIC(18,5))
#     RentalAmtPerMonth=Column(NUMERIC(18,5))
#     SoldDate=Column(DATETIME)
#     SoldAmt=Column(NUMERIC(18,5))
#     LatestMileage=Column(Integer)
#     AssetCode=Column(NVARCHAR(50))
#     SerialNumber=Column(NVARCHAR(50))
#     DCCode=Column(VARCHAR(20))
#     Currency=Column(VARCHAR(20))
#     DefaultStaffId=Column(VARCHAR(20),ForeignKey("MA_Staff.StaffUserId"))
#     FuelNorm=Column(VARCHAR(10))
#     GPSVendor=Column(VARCHAR(20))
#     Remarks=Column(NVARCHAR(1600))
#     EquipStatus=Column(VARCHAR(40))
# class MAContact(Base):
#     __tablename__="MA_Contact"
#     ContactCode=Column(VARCHAR(20),primary_key=True)
#     ContactName=Column(NVARCHAR(4000))
#     Addr1=Column(NVARCHAR(2560))
#     Addr2=Column(NVARCHAR(2560))
#     Addr3=Column(NVARCHAR(2560))
#     Addr4=Column(NVARCHAR(2560))
#     ZipCode=Column(VARCHAR(20))
#     Tel=Column(VARCHAR(30))
#     Fax=Column(VARCHAR(30))
#     CreateDate=Column(DATETIME)
#     CreateUser=Column(VARCHAR(20))
#     UpdateDate=Column(DATETIME)
#     UpdateUser=Column(VARCHAR(20))
#     IsUse=Column(CHAR(1))
#     ContactPerson=Column(NVARCHAR(2560))
#     TaxCode1=Column(VARCHAR(30))
#     TaxCode2=Column(VARCHAR(30))
#     ContactGroup=Column(VARCHAR(20))
#     Country=Column(VARCHAR(20))
#     SalesPersonId=Column(Integer)
#     ShortName=Column(NVARCHAR(50))
#     LacVietCode=Column(VARCHAR(50))
#     INVSerialNo=Column(VARCHAR(20))
#     INVFormID=Column(VARCHAR(20))
#     PaymentTerm=Column(Integer)
#     ExRateGroup=Column(VARCHAR(20))
# class EquipmentType(Base):
#     __tablename__="MA_EquipmentType"
#     EquipTypeNo=Column(VARCHAR(20),primary_key=True)
#     EquipTypeDesc=Column(NVARCHAR(640))
#     IsUse=Column(CHAR(1))
#     Volume=Column(NUMERIC(18,5))
#     VolumeUnit=Column(VARCHAR(20))
#     Weight=Column(NUMERIC(18,5))
#     WeightUnit=Column(VARCHAR(20))
#     Length=Column(NUMERIC(18,5))
#     Width=Column(NUMERIC(18,5))
#     Height=Column(NUMERIC(18,5))
#     DimUnit=Column(VARCHAR(20))
#     CreateDate=Column(DATETIME)
#     CreateUser=Column(VARCHAR(20))
#     UpdateDate=Column(DATETIME)
#     UpdateUser=Column(VARCHAR(20))
#     EquipmentGroup=Column(VARCHAR(20))
#     ConvertRate=Column(NUMERIC(18,7))
# class MACompanys(Base):
#     __tablename__="MA_Companys"
#     CompanyId=Column(VARCHAR(50),primary_key=True)
#     CompanyCode=Column(VARCHAR(50))
#     CompanyName=Column(NVARCHAR(4000))
#     Addr1=Column(NVARCHAR(2560))
#     Addr2=Column(NVARCHAR(2560))
#     Addr3=Column(NVARCHAR(2560))
#     Addr4=Column(NVARCHAR(2560))
#     ZipCode=Column(VARCHAR(20))
#     City=Column(VARCHAR(20))
#     Province=Column(NVARCHAR(50))
#     Country=Column(VARCHAR(20))
#     ContactPerson=Column(NVARCHAR(2560))
#     IsUse=Column(CHAR(1))
#     CreateDate=Column(DATETIME)
#     CreateUser=Column(VARCHAR(20))
#     UpdateDate=Column(DATETIME)
#     UpdateUser=Column(VARCHAR(20))
#     ContactCode=Column(VARCHAR(20))
#     Lat=Column(VARCHAR(20))
#     Lon=Column(VARCHAR(20))
#     AreaCode=Column(VARCHAR(20))
#     Tel=Column(VARCHAR(20))
#     WavePriority=Column(Integer)
#     CompanyGroup=Column(NVARCHAR(50))
#     SalesPerson=Column(NVARCHAR(50))
#     SalesPersonMobile=Column(VARCHAR(20))
#     ShopType=Column(VARCHAR(20))
# class MAStdCodes(Base):
#     __tablename__="MA_StdCodes"
#     CodeType=Column(VARCHAR(20),primary_key=True)
#     CodeID=Column(VARCHAR(30))
#     CodeDesc=Column(NVARCHAR(2560))
#     CodeVariant=Column(NVARCHAR(4000))
#     CodeNumeric=Column(NUMERIC(18,5))
#     IsUse=Column(Integer)
#     CreateDate=Column(DATETIME)
#     CreateUser=Column(VARCHAR(20))
#     UpdateDate=Column(DATETIME)
#     UpdateUser=Column(VARCHAR(20))
#     SeqNo=Column(Integer)
#     Tid=Column(Integer)
# Base.metadata.create_all(engine)
